### PR TITLE
Progression

### PR DESCRIPTION
**Pull request by felipe-clark**
@michellegasto ,

In this branch we have implemented the following:
1) Improved calendar design (button) #28 ;
2) Exercise progression #26;
3) Link from log to session summary #25;
4) Heart rate range calculator #24;
5) Color transition during session #23;
6) Fix x-axis on the log #20;
7) Validate min and max heart rate #16;
8) Create logout button #15;

Can you please pull this branch and test the changes before we merge?

Ritam and I have written the code together, so the code has been technically reviewed already.

Thank you.

### CODE REVIEW

**Comment by michellegasto** [comment]
Hi Felipe and Ritam,

Thanks again for the great work! 

I was able to check out the items in **bold**:

**Improved calendar design (button) #28 ;**
- Calendar design is more intuitive and the selection feature works well
- Typing in a later start date vs end date as well as and incorrect format and resulted in the "Invalid format..." message coming up

Exercise progression #26;

Link from log to session summary #25;

**Heart rate range calculator #24;**
- On signing up with my age the HR calculator was able to set the correct HR range

Color transition during session #23;

Fix x-axis on the log #20;

**Validate min and max heart rate #16;**
- too high of a range resulted in the error message "Invalid minimum or maximum..."
- may need change maximum HR limit to 150 (based on an 18 year old)

**Create logout button #15;**
- I was able to sign up, log out and sign in again.
- Unable to sign in with incorrect account
- Unable to sign in with incorrect password

Would you be able to provide me with the log in info for an account with exercise logs so I can check out the other functions?

**Comment by michellegasto** [comment]
With the a@a.com account:

**Exercise progression #26;**
- I was able to click on the notification bell and got the "Think about setting..

**Link from log to session summary #25;**
- I was able to click of several logs that led me to the appropriate session

**Fix x-axis on the log #20;**
- I am able to select an appropriate date rate
- Selecting a range beyond the saved sessions causes the app to crash or otherwise does not change the logs being shown - shows the previous logs for a correct range; clicking that previous log also causes the app to crash

**Comment by felipe-clark** [comment]
@michellegasto ,

Thank you for your feedback and for catching these issues. We are going to fix them soon.

**Comment by felipe-clark** [comment]
@michellegasto,
Thank you again for identifying these issues. All fixes were implemented. Could you please validate that you can no longer reproduce these bugs before we merge this branch to master?

Thank you.

**Comment by michellegasto** [comment]
The latest update looks good!

HR calculator
- new range limits work

Session Log
- selecting a date range without a session results in an empty graph

Best,
Michelle

**Comment by felipe-clark** [comment]
@michellegasto ,
Thank you for assuring the quality of the software.

Since everything looks good, I will proceed with the merge.

@haldarritam and @michellegasto , from now on, remember to switch back to the master branch and update it.

Thank you.

**Pull request merged**
