### PR TITLE
Add signup flow

### PR DESCRIPTION
**Pull request by felipe-clark**
@haldarritam and @michellegasto ,

In this branch I have created the whole signup flow. Could you please review these changes?
Please let me know if you think we should ask for some more user data in the signup page.

@michellegasto , could you please test this flow? Here are some things to validate:
1) You should not be able to login with an account that doesn't exist;
2) You should not be able to create an account with data that doesn't match the suggested patterns;
3) You should not be able to create two accounts for the same email;
4) Anything else you might want to try 😄 

Thank you.

### CODE REVIEW

**Comment by michellegasto** [comment]
@felipe-clark I tried signing in without an account and the log-in properly failed. However, when I signed in with a non-existent account, it prompted a log-in fail message but still brought me to the app.

I also can't seem to create an account - sign up button doesn't seem to do anything.

**Comment by felipe-clark** [comment]
@michellegasto ,

Sorry about that. I think I copied and pasted a line of code into the wrong place. After commit 
51e76b7 the issue should be fixed. 
Please pull the updates before testing again.

Note: because we did not foresee a sign-out button in our UI, with the current implementation there will be no way to sign-out and in again. So please try the failing cases first before trying a successful login.

When we meet tomorrow, we should remember to discuss where to include the log-out button.

**Comment by michellegasto** [comment]
Thanks for the fixing it @felipe-clark! With the updated code I have tried:
1) Logging in without an account --> "Login failed"
2) Signing up --> created account
3) Signing up with the same email --> "Email already in use" 
4) Logging in with correct email but wrong password --> "Login failed"
5) Logging in with correct email and password --> entered app
6) Signing up with weak password --> unable to continue
7) Signing up with mismatched password --> unable to continue
8) Signing up with only two alphanumeric values for name --> unable to continue

With regards to the data being asked for signing up I think that's probably enough since we have the settings page anyways.

**Comment by felipe-clark** [comment]
@michellegasto ,
Thank you for testing this workflow and for your feedback.  I am glad to hear everything is working as expecte.

Yesterday I met with Ritam and he gave me his in person 👍 for this merge request. Therefore, I will proceed with the merge.

Thank you.

**Pull request merged**
